import { createFileRoute } from "@tanstack/react-router";
import { useCallback,useEffect,useMemo,useState } from "react";
import { AlertTriangle,BarChart3,Bell,CheckCircle2,Clock3,Filter,Loader2,Plus,Search,TicketCheck,Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { AppShell } from "@/components/campus/app-shell";
import { ComplaintDialog } from "@/components/campus/complaint-dialog";
import { ComplaintDetails } from "@/components/campus/complaint-details";
import { StatusPipeline } from "@/components/campus/status-pipeline";
import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Switch } from "@/components/ui/switch";import { Textarea } from "@/components/ui/textarea";import { Toaster,toast } from "sonner";
import type { Complaint,Lookup,Notice,Profile,Role,Status } from "@/components/campus/types";import { statusLabel,statusOrder } from "@/components/campus/types";

export const Route=createFileRoute("/_authenticated/dashboard")({head:()=>({meta:[{title:"Dashboard — Campus Resolve"},{name:"description",content:"Manage and track campus complaints from submission to closure."},{property:"og:title",content:"Campus Resolve Dashboard"},{property:"og:description",content:"Role-based campus complaint management and tracking."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Dashboard});

function Dashboard(){const{user}=Route.useRouteContext();const[profile,setProfile]=useState<Profile|null>(null),[role,setRole]=useState<Role>('student'),[complaints,setComplaints]=useState<Complaint[]>([]),[categories,setCategories]=useState<Lookup[]>([]),[priorities,setPriorities]=useState<Lookup[]>([]),[notices,setNotices]=useState<Notice[]>([]),[staff,setStaff]=useState<Profile[]>([]),[people,setPeople]=useState<Profile[]>([]),[audit,setAudit]=useState<Array<{id:string;action:string;entity_type:string;created_at:string;details:unknown}>>([]),[tab,setTab]=useState('overview'),[selected,setSelected]=useState<Complaint|null>(null),[newOpen,setNewOpen]=useState(false),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[status,setStatus]=useState('all');
const load=useCallback(async()=>{const[{data:p},{data:r},{data:c},{data:pr}]=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).single(),supabase.from('user_roles').select('role').eq('user_id',user.id).single(),supabase.from('categories').select('*').order('name'),supabase.from('priorities').select('*').order('level')]);const activeRole=(r?.role||'student') as Role;setRole(activeRole);setProfile(p as Profile);setCategories((c||[]) as Lookup[]);setPriorities((pr||[]) as Lookup[]);const complaintQuery=supabase.from('complaints').select('*,categories(name),priorities(name,level),assignments(staff_id,is_current,profiles!assignments_staff_profile_fkey(display_name))').order('created_at',{ascending:false});const[{data:co},{data:no}]=await Promise.all([complaintQuery,supabase.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false})]);setComplaints((co||[]) as unknown as Complaint[]);setNotices((no||[]) as Notice[]);if(activeRole==='admin'){const[{data:s},{data:all},{data:a}]=await Promise.all([supabase.from('profiles').select('*').eq('is_active',true),supabase.from('profiles').select('*').order('display_name'),supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(100)]);const staffIds=(await supabase.from('user_roles').select('user_id').eq('role','staff')).data?.map(x=>x.user_id)||[];setStaff((s||[]).filter(x=>staffIds.includes(x.id)) as Profile[]);setPeople((all||[]) as Profile[]);setAudit(a||[])}setLoading(false)},[user.id]);
useEffect(()=>{void load();const channel=supabase.channel(`campus-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'complaints'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},payload=>{if(payload.eventType==='INSERT')toast.info((payload.new as Notice).title);void load()}).subscribe();return()=>{void supabase.removeChannel(channel)}},[load,user.id]);
async function signOut(){await supabase.auth.signOut();window.location.href='/'}
const filtered=useMemo(()=>complaints.filter(c=>(status==='all'||c.status===status)&&(`${c.ticket_number} ${c.title} ${c.location}`.toLowerCase().includes(search.toLowerCase()))),[complaints,search,status]);const unread=notices.filter(n=>!n.is_read).length;const active=complaints.filter(c=>!['closed','verified'].includes(c.status));const resolved=complaints.filter(c=>['resolved','verified','closed'].includes(c.status)).length;
if(loading||!profile)return <div className="loading-screen"><Loader2 className="animate-spin"/><span>Loading campus workspace…</span></div>;
return <AppShell profile={profile} role={role} tab={tab} setTab={setTab} unread={unread} onSignOut={signOut}><Toaster richColors position="top-right"/><div className="content-wrap"><header className="page-header"><div><p className="eyebrow">{role} workspace</p><h1>{tab==='overview'?'Good afternoon, '+profile.display_name.split(' ')[0]:tab[0].toUpperCase()+tab.slice(1)}</h1><p>{role==='student'?'Report issues and follow every step to resolution.':role==='staff'?'Focus on assigned work and keep students informed.':'Monitor service quality and keep teams accountable.'}</p></div>{role==='student'?<Button size="lg" onClick={()=>setNewOpen(true)}><Plus/>Raise complaint</Button>:null}</header>{tab==='overview'?<Overview role={role} complaints={complaints} active={active} resolved={resolved} notices={notices} onOpen={setSelected} onTab={setTab}/>:null}{tab==='complaints'?<ComplaintsView role={role} complaints={filtered} search={search} setSearch={setSearch} status={status} setStatus={setStatus} onOpen={setSelected}/>:null}{tab==='notifications'?<Notifications notices={notices} onChanged={load}/>:null}{role==='admin'&&tab==='people'?<People people={people} onChanged={load}/>:null}{role==='admin'&&tab==='settings'?<Settings categories={categories} priorities={priorities} onChanged={load}/>:null}{role==='admin'&&tab==='audit'?<Audit audit={audit}/>:null}</div><ComplaintDialog open={newOpen} onOpenChange={setNewOpen} userId={user.id} categories={categories} priorities={priorities} onCreated={load}/><ComplaintDetails complaint={selected} role={role} userId={user.id} staff={staff} onClose={()=>setSelected(null)} onChanged={load}/></AppShell>}

function Overview({role,complaints,active,resolved,notices,onOpen,onTab}:{role:Role;complaints:Complaint[];active:Complaint[];resolved:number;notices:Notice[];onOpen:(c:Complaint)=>void;onTab:(v:string)=>void}){const featured=active[0]||complaints[0];const stats=[['Total cases',complaints.length,TicketCheck],['Active now',active.length,Clock3],['Resolved',resolved,CheckCircle2],['Needs attention',complaints.filter(c=>['submitted','resolved'].includes(c.status)).length,AlertTriangle]];return <><section className="stats-grid">{stats.map(([label,value,Icon])=><div className="stat" key={label as string}><div><span>{label as string}</span><strong>{value as number}</strong></div><Icon className="stat-icon"/></div>)}</section><div className="dashboard-grid"><section className="primary-column"><div className="section-title"><div><p className="eyebrow">Priority view</p><h2>{featured?'Active complaint':'No active complaints'}</h2></div>{featured?<Button variant="outline" size="sm" onClick={()=>onOpen(featured)}>View details</Button>:null}</div>{featured?<article className="focus-case"><div className="case-top"><div><span className="ticket">{featured.ticket_number}</span><h3>{featured.title}</h3><p>{featured.location}</p></div><span className={`status-badge status-${featured.status}`}>{statusLabel[featured.status]}</span></div><StatusPipeline status={featured.status}/></article>:<div className="empty-state">Everything is clear for now.</div>}<div className="section-title"><h2>Recent complaints</h2><Button variant="ghost" size="sm" onClick={()=>onTab('complaints')}>View all</Button></div><ComplaintList complaints={complaints.slice(0,5)} onOpen={onOpen}/></section><aside className="secondary-column"><div className="section-title"><h2>Notifications</h2><Button variant="ghost" size="sm" onClick={()=>onTab('notifications')}>View all</Button></div><div className="notice-list">{notices.slice(0,4).map(n=><div className={n.is_read?'notice':'notice notice-new'} key={n.id}><Bell/><div><strong>{n.title}</strong><p>{n.message}</p><small>{new Date(n.created_at).toLocaleDateString()}</small></div></div>)}</div>{role==='admin'?<Reports complaints={complaints}/>:null}</aside></div></>}
function ComplaintList({complaints,onOpen}:{complaints:Complaint[];onOpen:(c:Complaint)=>void}){return <div className="complaint-list">{complaints.length?complaints.map(c=><button className="complaint-row" key={c.id} onClick={()=>onOpen(c)}><div><span className="ticket">{c.ticket_number}</span><strong>{c.title}</strong><small>{c.categories?.name} · {c.location}</small></div><div><span className={`status-badge status-${c.status}`}>{statusLabel[c.status]}</span><small>{new Date(c.created_at).toLocaleDateString()}</small></div></button>):<div className="empty-state">No complaints match this view.</div>}</div>}
function ComplaintsView({role,complaints,search,setSearch,status,setStatus,onOpen}:{role:Role;complaints:Complaint[];search:string;setSearch:(v:string)=>void;status:string;setStatus:(v:string)=>void;onOpen:(c:Complaint)=>void}){return <section><div className="toolbar"><div className="search-box"><Search/><Input aria-label="Search complaints" placeholder="Search ticket, issue, or location" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-box"><Filter/><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statusOrder.map(s=><option key={s} value={s}>{statusLabel[s]}</option>)}</select></div></div><div className="section-title"><h2>{role==='staff'?'Assigned complaints':'Complaint register'}</h2><span>{complaints.length} records</span></div><ComplaintList complaints={complaints} onOpen={onOpen}/></section>}
function Notifications({notices,onChanged}:{notices:Notice[];onChanged:()=>void}){async function read(id?:string){let q=supabase.from('notifications').update({is_read:true});q=id?q.eq('id',id):q.eq('is_read',false);await q;onChanged()}return <section><div className="section-title"><h2>Notifications</h2><Button variant="outline" onClick={()=>void read()}>Mark all read</Button></div><div className="notice-list full">{notices.map(n=><button className={n.is_read?'notice':'notice notice-new'} key={n.id} onClick={()=>void read(n.id)}><Bell/><div><strong>{n.title}</strong><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString()}</small></div></button>)}</div></section>}
function Reports({complaints}:{complaints:Complaint[]}){const grouped=Object.entries(complaints.reduce<Record<string,number>>((a,c)=>{const k=c.categories?.name||'Other';a[k]=(a[k]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...grouped.map(x=>x[1]));return <section className="report-panel"><div className="section-title"><div><p className="eyebrow">Live reporting</p><h2>Cases by category</h2></div><BarChart3/></div>{grouped.map(([name,count])=><div className="bar-row" key={name}><div><span>{name}</span><strong>{count}</strong></div><div><span style={{width:`${count/max*100}%`}}/></div></div>)}</section>}
function People({people,onChanged}:{people:Profile[];onChanged:()=>void}){async function toggle(p:Profile){const r=await supabase.from('profiles').update({is_active:!p.is_active}).eq('id',p.id);if(r.error)toast.error(r.error.message);else{toast.success('Account updated');onChanged()}}return <section><div className="section-title"><h2>User directory</h2><span>{people.length} accounts</span></div><div className="data-table">{people.map(p=><div className="person-row" key={p.id}><div className="avatar-initials">{p.display_name.slice(0,2).toUpperCase()}</div><div><strong>{p.display_name}</strong><small>{p.email} · {p.department||'No department'}</small></div><div className={p.is_active?'active-state':'inactive-state'}>{p.is_active?'Active':'Inactive'}</div><Switch checked={p.is_active} onCheckedChange={()=>void toggle(p)} aria-label={`Toggle ${p.display_name}`}/></div>)}</div></section>}
function Settings({categories,priorities,onChanged}:{categories:Lookup[];priorities:Lookup[];onChanged:()=>void}){const[name,setName]=useState(''),[desc,setDesc]=useState('');async function add(){if(name.trim().length<2)return toast.error('Enter a category name');const r=await supabase.from('categories').insert({name:name.trim(),description:desc.trim()||null});if(r.error)return toast.error(r.error.message);setName('');setDesc('');toast.success('Category created');onChanged()}async function toggle(table:'categories'|'priorities',id:string,on:boolean){const r=await supabase.from(table).update({is_active:!on}).eq('id',id);if(r.error)toast.error(r.error.message);else onChanged()}return <div className="management-grid"><section><div className="section-title"><h2>Complaint categories</h2></div><div className="data-table">{categories.map(c=><div className="setting-row" key={c.id}><div><strong>{c.name}</strong><small>{c.description}</small></div><Switch checked={c.is_active} onCheckedChange={()=>void toggle('categories',c.id,c.is_active)}/></div>)}</div></section><section className="form-panel"><h2>Add category</h2><Label htmlFor="cat-name">Name</Label><Input id="cat-name" value={name} onChange={e=>setName(e.target.value)} maxLength={80}/><Label htmlFor="cat-desc">Description</Label><Textarea id="cat-desc" value={desc} onChange={e=>setDesc(e.target.value)} maxLength={300}/><Button onClick={()=>void add()}><Plus/>Add category</Button><h2 className="priority-heading">Priority rules</h2>{priorities.map(p=><div className="priority-rule" key={p.id}><span><strong>{p.name}</strong><small>{p.response_hours}h response target</small></span><Switch checked={p.is_active} onCheckedChange={()=>void toggle('priorities',p.id,p.is_active)}/></div>)}</section></div>}
function Audit({audit}:{audit:Array<{id:string;action:string;entity_type:string;created_at:string;details:unknown}>}){return <section><div className="section-title"><h2>Audit log</h2><span>Most recent 100 events</span></div><div className="audit-list">{audit.map(a=><div key={a.id}><ShieldCheck/><div><strong>{a.action.replaceAll('.',' · ')}</strong><small>{a.entity_type} · {new Date(a.created_at).toLocaleString()}</small></div><code>{JSON.stringify(a.details)}</code></div>)}</div></section>}
